### ISSUE TITLE
Scroll on Filter options is not working 

### ISSUE THREAD

**Issue by felippemr** [globocom/database-as-a-service#185]
![scroll_error](https://cloud.githubusercontent.com/assets/2388162/4124132/ea1c39d6-32d5-11e4-90cf-88fce1b3537f.png)

**Comment by cyberelfo** [comment]
The same issue is happening in the Backup/Snapshots list.

**Comment by felippemr** [comment]
It is quite probable that e853c80 has introduced this behavior.
