### ISSUE TITLE
Could not find any downloads that satisfy the requirement

### ISSUE THREAD

**Issue by ninglianjie** [globocom/database-as-a-service#218]
Hi

```
  Could not find any downloads that satisfy the requirement python-faasclient==0.2.1 (from dbaas-nfsaas==0.6.10->-r requirements.txt (line 56))
Cleaning up...
No distributions at all found for python-faasclient==0.2.1 (from dbaas-nfsaas==0.6.10->-r requirements.txt (line 56))
```

**Comment by ninglianjie** [comment]
No distributions at all found for foxha==0.7.0.7 (from dbaas-foxha==0.2.6->-r requirements.txt (line 66))

**Comment by otherpirate** [comment]
Hi @ninglianjie, sorry about it :(

I updated the dbaas-foxha requirement to foxha==0.9.2

About the python-faasclient, it's a internal File System solution, will be published soon. (I will keep this issue open until)
You can use the dbaas-nfsaas==0.6.7, the problem will no happen.

**Comment by otherpirate** [comment]
Hi @ninglianjie 

We updated the requirements, you should not have problems now! 

Any problem, please, let me know

**Comment by ninglianjie** [comment]
OK, thanks
